### PR TITLE
Fix/webapp setup

### PR DESCRIPTION
**Pull request by timiskhakov**
Hi. Thanks for the useful library! I've added a couple of bells and whistles to the sample app for my own convenience:
- Fixed launch settings
- Added swagger
- Added db creation and auto migrations during the app startup

Maybe these changes would be useful for the upstream as well. If not, please feel free to close this PR without merging.

### CODE REVIEW

**Comment by wcabus** [comment]
Thanks for the pull request! I will take some of the improvements and apply them manually, because I'm currently splitting the code base up into multiple repositories for clarity. One thing however: migrating a EF database in the `Startup.Configure` method is not a best practice: Configure will be executed for every API call and could block future EF migrations from being created.

**Comment by timiskhakov** [comment]
Glad to be helpful! Although I think this part:
> Configure will be executed for every API call and could block future EF migrations from being created

is a bit misleading. According to [the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.2#the-configure-method) `Configure` is used to set up how the app responses to API calls. It's intended to fire on app startup, not on every request.

**Comment by wcabus** [comment]
You're right, I think I was thinking about something else or related to an older version of ASP.NET Core... But in any case, I was already using EnsureCreatedAsync in the Program class, which is not compatible with migrations, so I went ahead and applied migrations in Program.cs in order to be future-proof.

**Comment by wcabus** [comment]
Your fixes have been applied in the new repo https://github.com/ruh-roh/Samples-AspNetCore :)

**Pull request closed without merging**
